library(SeuratExtend)
library(Seurat)
library(tidyverse)
library(dplyr)
library(mosaic)
library(rlist)
library(purrr)
library(roxygen2)
library(sinew)
options(max.print = 100, spe = "human", nCores = 12)

usethis::use_data(human_ensembl_genesymbol, overwrite = TRUE)
usethis::use_gpl_license(version = 3, include_future = TRUE)
rmarkdown::render("vignettes/Trajectory.Rmd", output_format = "md_document")
makeOxygen(save_colors)
roxygenize()
pkgdown::build_site(examples = FALSE)
pkgdown::build_home()
pkgdown::build_articles()
pkgdown::build_article(name = "SCENIC", quiet = F)
